### ISSUE TITLE
Have to reload the page after disabling 2-factor authentication to see the changed

### ISSUE THREAD

**Issue by thesea2201** [flashvpsdev/issues#4]
I disabled 2-factor authentication but the page did not change the status in view. Everything is good after I reloaded the page.
![image](https://user-images.githubusercontent.com/21289697/131660894-b41c70d2-a718-4945-a889-bc8303387d35.png)
![image](https://user-images.githubusercontent.com/21289697/131662443-aefe602b-743f-4bf1-b872-a76e59044590.png)

**Comment by nguyentranchung** [comment]
cảm ơn @thesea2201 đã gửi vấn đề nhé 💌

bên mình đã sửa lỗi này rồi ✅
