### ISSUE TITLE
Login form does not show error message

### ISSUE THREAD

**Issue by thesea2201** [flashvpsdev/issues#5]
I click sign in and nothing happens, this is what I captured.
![image](https://user-images.githubusercontent.com/21289697/131674311-8442fbc4-0c0a-42df-a639-d7126a958856.png)
![image](https://user-images.githubusercontent.com/21289697/131675144-1a5df464-64d7-4d01-87b3-e7dee2d0e642.png)

**Comment by nguyentranchung** [comment]
![Screenshot from 2021-09-05 07-57-53](https://user-images.githubusercontent.com/9611224/132110793-35c66c6f-30b3-46f5-ae59-c8c2aac723df.png)

Em đã fix, cảm ơn a rất nhiều ạ
