### ISSUE TITLE
Could not verify the account after the verify link is expired

### ISSUE THREAD

**Issue by thesea2201** [flashvpsdev/issues#6]
Could not verify the account after the verify link is expired. So, I can not log in anymore except the first time

**Comment by nguyentranchung** [comment]
@thesea2201 

Khi a liên kết xác nhận email sẽ được đưa về trang login, anh có thể đăng nhập lại tài khoản anh đã tạo sau đó yêu cầu cấp lại liên kết xác minh email rồi nhé.

![Screenshot from 2021-09-05 11-22-12](https://user-images.githubusercontent.com/9611224/132112790-8acc692e-a8b9-472a-8481-d45f0efc8fe3.png)

**Comment by nguyentranchung** [comment]
![Screenshot from 2021-09-05 12-39-20](https://user-images.githubusercontent.com/9611224/132114162-f9f989ee-4eea-4a7b-8b1d-d09e03040015.png)

Trang profile đã được phép access nhưng sẽ hiện 1 chú ý.
