### ISSUE TITLE
Stuck in installing when occurring error

### ISSUE THREAD

**Issue by thesea2201** [flashvpsdev/issues#7]
I'm stuck in installing when occurring error, I couldn't delete or reinstall the server.
![image](https://user-images.githubusercontent.com/21289697/131688374-346f6ae7-2937-4547-b23b-117f3371df30.png)
![image](https://user-images.githubusercontent.com/21289697/131688462-973201ea-c8df-45b5-9171-508757a307a6.png)

**Comment by nguyentranchung** [comment]
Cuối tuần e sẽ lên bản cập nhật mới fix lỗi này ạ

**Comment by nguyentranchung** [comment]
@thesea2201 em đã cho phép xóa máy chủ nếu cài đặt bị lỗi rồi nha a
